### ISSUE TITLE
Can I use the macos 10.15.4?

### ISSUE THREAD

**Issue by Unknown-parameters** [vantuan88291/clover-xps13-9343#2]
Can I finish the thing ,use  macos 10.15.4 with your the EFI?
Please tell me,thank you.

**Comment by vantuan88291** [comment]
Hi, i want to upgrade to catalina 10.15.4 too, but now i am using 10.14.6 with this EFI, it still very good for now, i guess this efi can work with catalina but it will miss some kext and you have to fix it. Please try it and tell me if you have successful. Thanks

**Comment by Unknown-parameters** [comment]
Thank you for your answer.
I can't express myself well enough in English and hope you can understand .
 In fact ,Only yesterday did I know the concept .Fortunately, I found your plan here.
As a new hand,i need to know how to use this EFI .If I finish your design, I will try to update it.
Thanks your help.

**Comment by vantuan88291** [comment]
This is not an EFI folder. You know the efi folder include a folder is: CLOVER, inside it has kext, driver...etc what we need, this repo github is inside of clover folder. And all things we need just clover folder inside efi folder. So you have to replace all things inside your EFI/CLOVER with this repo and just do what you need

**Comment by vantuan88291** [comment]
I was update for 10.15.6, please checkout at catalina branch

**Comment by Unknown-parameters** [comment]
> I was update for 10.15.6, please checkout at catalina branch

That's good news.
